
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud-work
  name: cloud-work
  namespace: cn202002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-work
  template:
    metadata:
      labels:
        app: cloud-work
    spec:
      imagePullSecrets:
        - name: cn202002
        - password: cn202002
      containers:
      - image: harbor.edu.cn/cn202002/cloud_work:{VERSION}
        name: cloud-work
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-work
  labels:
    app: cloud-work
spec:
  type: NodePort
  selector:
    app: cloud-work
  ports:
  - name: tcp
    protocol: TCP
    port: 8998
    targetPort: 8998
    nodePort: 30001
